### ISSUE TITLE
Understanding limitation of dbo schema

### ISSUE THREAD

**Issue by mnsrulz** [LycanII/LzScripts#11]
First of I would like to thank you for writing and maintaining this nice plugin. While I was looking at how easy it is to generate scripts for existing data, I found that it's limited to dbo schema only (already documented). This made me wonder what difficulties or challenges you found in expanding it to other schemas. I am not too familiar with writing the plugins for vscode but if you can provide some input maybe I can contribute a little here if at all I can.

**Comment by LycanII** [comment]
Hi @mnsrulz , 
I am glad you reached out, 
I am also happy this little tool has been of help to you :) 

The truth is it supports only _dbo_  because I hard-coded _dbo_ in some parts of the code, specifically here 

![image](https://user-images.githubusercontent.com/49438182/203773353-99720057-1c13-44ae-b4ef-f305f34cbd84.png)

this is the part of the code that tries to find the Table part of a select query.  Aptly named the place of Sadness.

I will take a look at it again and see how best we can change that. 
I will reach out to you if need help hope you don't mind ?

Thanks so much,

**Comment by LycanII** [comment]
I have now removed the dbo limitation :) 
Happy coding :)

**Comment by mnsrulz** [comment]
Awesome thank you so much!
